services:
  client:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/db2
    depends_on:
      - mongo
    platform: linux/amd64

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/db2/db2

volumes:
  mongo-data:
